name: docker

on:
  push:

jobs:
  temp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}
          tags: ghcr.io/niekcandaele/aws-graviton-hackathon:latest
          context: ./temp-container
      - name: Image digest
        run: echo ${{ steps.docker_build_server.outputs.digest }}
